#include "wheel_leg_math.h"

#include <math.h>

/* Five-bar leg forward kinematics generated by MATLAB and simplified by hand. */
void WheelLegPosition(float phi1, float phi4, float position[2])
{
    const float xb = 0.05f * cosf(phi1);
    const float yb = 0.05f * sinf(phi1);
    const float xd = 0.06f + 0.05f * cosf(phi4);
    const float yd = 0.05f * sinf(phi4);
    const float a0 = 0.21f * (xd - xb);
    const float b0 = 0.21f * (yd - yb);
    const float c0 = (xd - xb) * (xd - xb) + (yd - yb) * (yd - yb);
    const float discriminant = a0 * a0 + b0 * b0 - c0 * c0;

    if (discriminant < 0.0f)
    {
        position[0] = NAN;
        position[1] = NAN;
        return;
    }

    const float phi2 = 2.0f * atanf((b0 + sqrtf(discriminant)) / (a0 + c0));
    const float xc = xb + 0.105f * cosf(phi2);
    const float yc = yb + 0.105f * sinf(phi2);

    position[0] = sqrtf((xc - 0.03f) * (xc - 0.03f) + yc * yc);
    position[1] = atan2f(yc, xc - 0.03f);
}
